easy_admin:

  site_name: '<span style="font-size:25px;">Projet des Projets</span>'

  formats:
    datetime: 'd/m/Y H:i:s'
    date: 'd/m/Y'

  list:
    max_results: 22
    actions:
      - { name: 'show', icon: 'eye'}
      - { name: 'edit', icon: 'pencil'}
      - { name: 'delete', icon: 'trash'}

  design:
    assets:
      css:
        - '/css/admin.css'
    menu:
          - { entity: 'User', label: 'Gestion des Utilisateurs', icon: 'user' }
          - { entity: 'Validation', label: 'Validation des Présentations', icon: 'check' }
          - { entity: 'Report', label: 'Messages pour les Administrateurs', icon: 'comment-alt' }
          - { entity: 'Slideshows', label: 'Diaporamas', icon: 'tablet-alt' }
          - { entity: 'RolesManage', label: 'Gestion des Rôles Administrateurs', icon: 'users', permission: 'ROLE_MASTER_ADMIN' }

  entities:

    Slideshows:
      class: App\Entity\Slide
      edit:
        fields:
          - slideName
          - textContent
          - caption
          - url
     

    RolesManage:
      class: App\Entity\User
      list:
        fields:
          - id
          - name
          - email
          - userRoles
          - isAllowed
      edit:
        fields:
          - name
          - email
          - userRoles

    User:
      class: App\Entity\User
      list:
        fields:
          - id
          - name
          - email
      show:
        fields:
          - id
          - name
          - email
          - isAllowed
          - isAllowedComment
      edit:
        fields:
          - name
          - email
          - isAllowed
          - isAllowedComment

    Validation:
      class: App\Entity\PPBasic
      list:
        fields:
          - id
          - title
          - adminValidation
      show:
        fields:
          - id
          - adminValidation
      edit:
        fields:
          - adminValidation

    Report:
      class: App\Entity\Report
      label: 'Messages'
      list:
        #dql_filter: 'entity.id < 10'
        fields:
          - id
          - createdAt
          - context
          - user.id
          - user.email
