# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers :
        default :
            web_path : ~

    filter_sets :
        cache : ~

        # Slideshow Thumbnails
        slide_thumbnail :

            # list of transformations to apply
            filters :

                # create a thumbnail: set size to 90x50 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail  : { size : [80, 50], mode : outbound }


        # Projects Logos Thumbnails (medium)
        logo_thumbnail_md:

            # list of transformations to apply
            filters:

                # use and setup the "scale" filter
                scale:

                    # input ?x? px -> output ?x? px (relative down-scale)
                    dim: [ 140, 140 ]

        # Projects Logos Thumbnails (small)
        logo_thumbnail_sm:

            # list of transformations to apply
            filters:

                # use and setup the "scale" filter
                scale:

                    # input ?x? px -> output ?x? px (relative down-scale)
                    dim: [ 110, 110 ]


        # the name of the "filter set"
        my_thumb :

            # adjust the image quality to 75%
            quality : 75

            # list of transformations to apply (the "filters")
            filters :

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail  : { size : [120, 90], mode : outbound }

                # create a 2px black border: center the thumbnail on a black background
                # 4px larger to create a 2px border around the final image
                background : { size : [124, 94], position : center, color : '#000000' }
