vich_uploader:
    db_driver: orm

    mappings:

        project_logo_image:
            
            uri_prefix: /images/project/logos
            upload_destination: '%kernel.project_dir%/public/images/projects/logos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        project_logo_thumbnail:
            
            uri_prefix: /images/project/thumbnails
            upload_destination: '%kernel.project_dir%/public/images/projects/thumbnails'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true


        project_document_file:
                    
            uri_prefix: /files/project/documents
            upload_destination: '%kernel.project_dir%/public/files/projects/documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        project_teammate_image:

            uri_prefix: /images/project/teammates
            upload_destination: '%kernel.project_dir%/public/images/projects/teammates'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        persorg_image:

            uri_prefix: /images/persorgs
            upload_destination: '%kernel.project_dir%/public/images/persorgs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        news_image:

            uri_prefix: /images/news
            upload_destination: '%kernel.project_dir%/public/images/news'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            
 
        slide_image:

            uri_prefix: /images/projects/slides_images
            upload_destination: '%kernel.project_dir%/public/images/projects/slides_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true